### ISSUE TITLE
Build Instructions Fails To Build

### ISSUE THREAD

**Issue by jlpoolen** [harshil1991/ffserver#2]
jlpoole@taurus /usr/local/src $ git clone https://github.com/harshil1991/ffserver.git
Cloning into 'ffserver'...
remote: Enumerating objects: 48, done.
remote: Total 48 (delta 0), reused 0 (delta 0), pack-reused 48
Receiving objects: 100% (48/48), 6.45 MiB | 6.27 MiB/s, done.
Resolving deltas: 100% (20/20), done.
jlpoole@taurus /usr/local/src $ cd ffserver/
jlpoole@taurus /usr/local/src/ffserver $ ls
README.md  buildFFServer.sh  ffserver  ffserver.c  ffserver.conf  ffserver.h
jlpoole@taurus /usr/local/src/ffserver $ ./buildFFServer.sh
In file included from ffserver.c:20:
ffserver.h:35:10: fatal error: libavformat/url.h: No such file or directory
 #include <libavformat/url.h>
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
Done
jlpoole@taurus /usr/local/src/ffserver $

**Comment by harshil1991** [comment]
seems like you have not installed ffmpeg.
